// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYCp4G8b7qCVgoDFANDadcyKWZexX46_Y',
    appId: '1:284941394691:web:f622b8e509fb12f6fb7f36',
    messagingSenderId: '284941394691',
    projectId: 'flutter-notifications-90b77',
    authDomain: 'flutter-notifications-90b77.firebaseapp.com',
    storageBucket: 'flutter-notifications-90b77.firebasestorage.app',
    measurementId: 'G-Y1Q49GCEGV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRI9Yr-eBCeJwIcDgGRAQ5gbr32W3z36E',
    appId: '1:284941394691:android:5a0679085c2484fefb7f36',
    messagingSenderId: '284941394691',
    projectId: 'flutter-notifications-90b77',
    storageBucket: 'flutter-notifications-90b77.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5XT2YZu1yii11ieRaCLNxEE1CTDvLWkk',
    appId: '1:284941394691:ios:c46bf1342d5a1b85fb7f36',
    messagingSenderId: '284941394691',
    projectId: 'flutter-notifications-90b77',
    storageBucket: 'flutter-notifications-90b77.firebasestorage.app',
    iosBundleId: 'com.example.flutterNotifications',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5XT2YZu1yii11ieRaCLNxEE1CTDvLWkk',
    appId: '1:284941394691:ios:c46bf1342d5a1b85fb7f36',
    messagingSenderId: '284941394691',
    projectId: 'flutter-notifications-90b77',
    storageBucket: 'flutter-notifications-90b77.firebasestorage.app',
    iosBundleId: 'com.example.flutterNotifications',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYCp4G8b7qCVgoDFANDadcyKWZexX46_Y',
    appId: '1:284941394691:web:e1640fcd9ca9fdcafb7f36',
    messagingSenderId: '284941394691',
    projectId: 'flutter-notifications-90b77',
    authDomain: 'flutter-notifications-90b77.firebaseapp.com',
    storageBucket: 'flutter-notifications-90b77.firebasestorage.app',
    measurementId: 'G-STV3V36T2Y',
  );
}
